import Contact from '@/app/Contact/content'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     <Contact>
      <body>{children}</body>
      </Contact>
    </html>
  )
}
